Repository evhub/coconut, pull requests merged in 2018-11, with the labels that each got.

#452 Expand documentation on TCO/TRE
  DOCS.md
Labels: documentation

#453 Improve enhanced type annotation docs on sequences
  DOCS.md
Labels: documentation, resolved

#458 Add __hash__ on data types
  coconut/compiler/compiler.py
  tests/src/cocotest/agnostic/main.coco
Labels: bounty: $30, enhancement, resolved

#461 Fix addpattern incorrectly catching all MatchErrors
  coconut/compiler/compiler.py
  coconut/compiler/header.py
  coconut/compiler/matching.py
  coconut/compiler/templates/header.py_template
  coconut/constants.py
  coconut/root.py
  coconut/stubs/__coconut__.pyi
  tests/src/cocotest/agnostic/suite.coco
Labels: bounty: $50, oversight
